### ISSUE TITLE
ERROR on /tpahere

### ISSUE THREAD

**Issue by zoredache** [versox/HorseTeleport#2]
This happens when the `/tpahere` is sent, not when the `/tpaccept` is used.  Perhaps [this](https://github.com/versox/HorseTeleport/blob/master/src/main/java/Listener/TeleportListener.java#L33) should just be on `/tpaccept`?

```
[2016-01-26 04:45:23] [Server thread/INFO]: Ohhani10 issued server command: /tpahere Zoredache
[2016-01-26 04:45:23] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to HorseTeleport v1.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66-internal]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66-internal]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
Caused by: java.lang.NullPointerException
    at HorseTeleport.HorseTeleporter.teleport(HorseTeleporter.java:10) ~[?:?]
    at Listener.TeleportListener.onCommandExecute(TeleportListener.java:43) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor230.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
    ... 16 more
```

**Comment by versox** [comment]
I'm aware of this issue. I'm still trying to figure out how to handle tpa's and tpahere's. In these cases the player issuing the command is not the one teleporting and the player is not teleporting right away because the other player still needs to issue tpaccept. That makes things a little more complicated
