### ISSUE TITLE
Attempted to manually compile, gets a missing `plugin.yml`

### ISSUE THREAD

**Issue by zoredache** [versox/HorseTeleport#3]
I am trying with

```
git clone https://github.com/versox/HorseTeleport.git
cd HorseTeleport
mvn clean package
```

Resulting jar has this contents.

```
$ unzip -l target/HorseTeleport-0.0.1-SNAPSHOT.jar
Archive:  target/HorseTeleport-0.0.1-SNAPSHOT.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2016-01-26 03:46   META-INF/
      141  2016-01-26 03:46   META-INF/MANIFEST.MF
        0  2016-01-26 03:46   Listener/
        0  2016-01-26 03:46   HorseTeleport/
     2130  2016-01-26 03:46   Listener/TeleportListener.class
      876  2016-01-26 03:46   HorseTeleport/HorseTeleport.class
     1285  2016-01-26 03:46   HorseTeleport/HorseTeleporter.class
        0  2016-01-26 03:46   META-INF/maven/
        0  2016-01-26 03:46   META-INF/maven/me.verso.com/
        0  2016-01-26 03:46   META-INF/maven/me.verso.com/HorseTeleport/
     1044  2016-01-25 22:32   META-INF/maven/me.verso.com/HorseTeleport/pom.xml
      119  2016-01-26 03:46   META-INF/maven/me.verso.com/HorseTeleport/pom.properties
---------                     -------
     5595                     12 files
```

And this error on startup.

```
[2016-01-26 03:18:28] [Server thread/ERROR]: Could not load 'plugins/HorseTeleport-0.0.1-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more
```

**Comment by versox** [comment]
@zoredache Try using a maven clean install?
